distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.4.0
install_time: "Sat Sep  5 13:14:57 2020"
installation_id: "dea35cfa-c5ef-46ae-a06b-b2900ee547a4"
rime_version: 1.5.3