# Window
window:
  decorations: none
  startup_mode: SimpleFullscreen
  scrolling:
    history: 5000
    multiplier: 3

# Font
font:
  normal:
    family: SFMono Nerd Font
    style: Regular
  bold:
    family: SFMono Nerd Font
    style: Bold
  italic:
    family: SFMono Nerd Font
    style: Italic
  bold_italic:
    family: SFMono Nerd Font
    style: Bold Italic
  size: 20.0
  offset:
    y: 10
    x: 0
  glyph_offset:
    y: 5
    x: 0
  use_thin_strokes: true

# Background opacity
background_opacity: 0.7
